# Generated by Django 3.2.14 on 2022-08-26 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(related_name='subjects', through='lessons.LearningActivity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningactivity',
            name='rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.class', verbose_name='Помещение'),
        ),
        migrations.AddField(
            model_name='learningactivity',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='learningactivity',
            name='teachers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ManyToManyField(related_name='rooms', through='lessons.LearningActivity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_subject_name'),
        ),
        migrations.AddConstraint(
            model_name='learningactivity',
            constraint=models.UniqueConstraint(fields=('subjects', 'rooms', 'teachers'), name='unique_lesson'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_classroom_name'),
        ),
    ]
