# Generated by Django 4.1 on 2022-08-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='class',
            name='unique_classroom_name',
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_classroom_name'),
        ),
    ]
