# Generated by Django 4.1 on 2022-08-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_class_unique_classroom_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='learningactivity',
            name='unique_lesson',
        ),
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_subject_name',
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Номер помещения'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Предмет'),
        ),
        migrations.AddConstraint(
            model_name='learningactivity',
            constraint=models.UniqueConstraint(fields=('id', 'subjects', 'rooms', 'teachers'), name='unique_lesson'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_subject_name'),
        ),
    ]
