# Generated by Django 4.1 on 2022-08-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_learningactivity_unique_lesson_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='learningactivity',
            name='unique_lesson',
        ),
        migrations.AddConstraint(
            model_name='learningactivity',
            constraint=models.UniqueConstraint(fields=('subjects', 'rooms', 'teachers'), name='unique_lesson'),
        ),
    ]
